---
#Tasks file to install Docker
    - name: 1.0 - Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: 1.1 - Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: 1.2 - Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: 1.3 - Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: 1.4 - Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

#    - name: 1.5 - Install Docker Module for Python
 #     pip:
   #     name: docker
